-- MySQL Script generated by MySQL Workbench
-- Tue Sep  8 20:38:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Empresa_tech
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Empresa_tech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Empresa_tech` DEFAULT CHARACTER SET utf8 ;
USE `Empresa_tech` ;

-- -----------------------------------------------------
-- Table `Empresa_tech`.`Departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa_tech`.`Departamentos` (
  `Setor` VARCHAR(45) NOT NULL,
  `Codigo_do_departamento` INT NOT NULL,
  PRIMARY KEY (`Codigo_do_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empresa_tech`.`Supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa_tech`.`Supervisor` (
  `idSupervisor` CHAR(1) NOT NULL,
  `Nome_supervisor` VARCHAR(45) NULL,
  PRIMARY KEY (`idSupervisor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empresa_tech`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa_tech`.`Funcionarios` (
  `idFuncionarios` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `Cpf` VARCHAR(45) NOT NULL,
  `Salario` DECIMAL(8,6) NOT NULL,
  `Codigo_do_departamento` INT NOT NULL,
  `idSupervisor` CHAR(1) NOT NULL,
  PRIMARY KEY (`idFuncionarios`),
  INDEX `fk_Funcionarios_1_idx` (`Codigo_do_departamento` ASC),
  INDEX `fk_Funcionarios_2_idx` (`idSupervisor` ASC),
  CONSTRAINT `fk_Funcionarios_1`
    FOREIGN KEY (`Codigo_do_departamento`)
    REFERENCES `Empresa_tech`.`Departamentos` (`Codigo_do_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionarios_2`
    FOREIGN KEY (`idSupervisor`)
    REFERENCES `Empresa_tech`.`Supervisor` (`idSupervisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empresa_tech`.`Atas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa_tech`.`Atas` (
  `Nome_da_etapa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nome_da_etapa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empresa_tech`.`Projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa_tech`.`Projetos` (
  `idProjetos` INT NOT NULL,
  `Nome_do_projeto` VARCHAR(45) NOT NULL,
  `Data_Inicial` DATE NOT NULL,
  `id_fases` INT NOT NULL,
  `Nome_da_etapa` VARCHAR(45) NOT NULL,
  INDEX `fk_Atas_1_idx` (`Nome_da_etapa` ASC),
  PRIMARY KEY (`Nome_da_etapa`),
  CONSTRAINT `fk_Atas_1`
    FOREIGN KEY (`Nome_da_etapa`)
    REFERENCES `Empresa_tech`.`Atas` (`Nome_da_etapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empresa_tech`.`Dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa_tech`.`Dependentes` (
  `idDependentes` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Idade` VARCHAR(45) NOT NULL,
  `idFuncionarios` INT NOT NULL,
  INDEX `fk_Dependentes_1_idx` (`idFuncionarios` ASC),
  CONSTRAINT `fk_Dependentes_1`
    FOREIGN KEY (`idFuncionarios`)
    REFERENCES `Empresa_tech`.`Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empresa_tech`.`Funcionarios_Projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa_tech`.`Funcionarios_Projetos` (
  `Funcionarios_idFuncionarios` INT NOT NULL,
  `Projetos_Nome_da_etapa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Funcionarios_idFuncionarios`, `Projetos_Nome_da_etapa`),
  INDEX `fk_Funcionarios_has_Projetos_Projetos1_idx` (`Projetos_Nome_da_etapa` ASC),
  INDEX `fk_Funcionarios_has_Projetos_Funcionarios1_idx` (`Funcionarios_idFuncionarios` ASC),
  CONSTRAINT `fk_Funcionarios_has_Projetos_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idFuncionarios`)
    REFERENCES `Empresa_tech`.`Funcionarios` (`idFuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionarios_has_Projetos_Projetos1`
    FOREIGN KEY (`Projetos_Nome_da_etapa`)
    REFERENCES `Empresa_tech`.`Projetos` (`Nome_da_etapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
